### ISSUE TITLE
Options are not dynamic

### ISSUE THREAD

**Issue by mickeyvip** [fiestah/angular-money-directive#13]
Hi and thank you.

I have a situation where I need to dynamically set `min`, `max` and `precision`, but right now the directive preserves the initial values it finds.

Thank you.

**Comment by slayful** [comment]
+1

**Comment by thatmarvin** [comment]
Fixed on v1.1.0.

Note that this doesn't preserve the fractions. E.g. say the value is `12.345` and precision is `1`, the value gets rounded to `12.3`. If the precision changes to `3`, the value is now `12.300`, not `12.345`. Hope that works for your use case!
