### ISSUE TITLE
Always dirty

### ISSUE THREAD

**Issue by ekzarov** [fiestah/angular-money-directive#21]
Thank you for your solution!

There is very big issue I think. If I put your directive to my input, angular form become dirty from the start.
Are you plan to fix this in nearest time, because I want to use your directive in my project?

Thank you.

**Comment by bhushangahire** [comment]
I am facing the same issue have you got any solution to this ?

**Comment by brnogz** [comment]
same here, i thin, there is no news about it, right?

**Comment by thatmarvin** [comment]
I apologize for the neglect! This should now be fixed.
