### ISSUE TITLE
Formatting issue on initial rendering

### ISSUE THREAD

**Issue by loosebits** [fiestah/angular-money-directive#24]
I have this:

    <input type='text' precision='2' max='99999999999.99' min='0.01' ng-model='salary' />

The value in the model is 0.01.  It is being displayed as 0 until you visit the field and tab out.  This is due to ngModelCtrl.$render() not being called in the  precision observe callback,

**Comment by KieranDotCo** [comment]
Used your fix on our project and has fixed our issue :) 

Many Thanks @loosebits :+1:

**Comment by thatmarvin** [comment]
This should now be fixed.
