### ISSUE TITLE
Does not work with AngularJS 1.3.7

### ISSUE THREAD

**Issue by leonbrag** [fiestah/angular-money-directive#27]
Directive does not seem to work with 1.3.7, but does work with 1.2.25

**Comment by thatmarvin** [comment]
I pointed the [demo page](https://fiestah.github.io/angular-money-directive/) to use 1.3.7 and it works just fine. All tests pass as well.

Make sure you're using v1.2.x if you're on Angular 1.3.x and up, or 1.1.x if you're on Angular 1.2.

**Comment by thatmarvin** [comment]
You can now look at different angular versions on the demo page.
