### ISSUE TITLE
Non-numerics are still valid.

### ISSUE THREAD

**Issue by psrivongse** [fiestah/angular-money-directive#28]
Love the directive, works great except whenever I press a non-numeric character twice in the field it is inputted into the field. Just a little bug, the ng-model is still the correct format however.
![screen shot 2015-10-19 at 7 48 13 pm](https://cloud.githubusercontent.com/assets/1300226/10596556/5a33dfc2-769a-11e5-8c81-f62a03739d28.png)

![screen shot 2015-10-19 at 7 45 33 pm](https://cloud.githubusercontent.com/assets/1300226/10596519/f9ef1316-7699-11e5-927e-e95e1bdf138a.png)

**Comment by thatmarvin** [comment]
This should be fixed in v1.2.1. Thanks for reporting!
