### ISSUE TITLE
Strict DI Error

### ISSUE THREAD

**Issue by OmriAharon** [fiestah/angular-money-directive#29]
Directive definitions do not follow the minification guildelines:

`.directive('money', function($parse) { ... })`

Should be

`.directive('money', ['$parse', function($parse) { ... }])`

Can you please fix?

**Comment by thatmarvin** [comment]
The files in `dist` are correctly annotated. I'll fix `package.json` to point to that though.

**Comment by OmriAharon** [comment]
Hey, thanks for fixing :)

However the main in bower.json still points to the non-dist one, can you change to "./dist/angular-money-directive.js" please?

**Comment by thatmarvin** [comment]
@OmriAharon done in v1.2.3
