### ISSUE TITLE
Directive only works when not minified

### ISSUE THREAD

**Issue by gantaa** [fiestah/angular-money-directive#30]
The directive's module can no longer be loaded after code is minified.  I did not see an $inject array with string parameters for your injection.  

See here: https://docs.angularjs.org/tutorial/step_05#a-note-on-minification

**Comment by thatmarvin** [comment]
Did you happen to install from bower? The annotated files are actually in `./dist`. Updated the readme to point that out, is that any clearer?

**Comment by gantaa** [comment]
I did install with bower.  Perfect.  Works now.  Thanks!
