### ISSUE TITLE
How to disallow plus sign within the text box ?

### ISSUE THREAD

**Issue by sijo-vijayan** [fiestah/angular-money-directive#35]
Hi,
I'm able enter + sign within the text box, How can i avoid this ?
Example : +444.22

First i will enter a number like 444.22 and then i can add + symbol at the beginning of the text box.

**Comment by thatmarvin** [comment]
What's wrong with the plus sign? It's a valid symbol in a number so I don't think the directive should disallow it.

If you don't want this behavior, you can fork the repo and remove the `+` from `NUMBER_REGEXP` in the source code.

**Comment by sijo-vijayan** [comment]
I thought it does't allow plus sign because i can't enter plus sign initially. I will update my code.

Thanks
